<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please transfer the total amount to t_a6d3bd</name>
   <tag></tag>
   <elementGuidId>848f0837-c7e2-43cc-b439-c41f7f64fc22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm Order&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0765b275-55ce-43d3-b725-3981bb88e2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6eb5073d-7e36-4a2a-9987-fe0dc5263ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm Order</value>
      <webElementGuid>d9105586-8e18-4359-8f88-b09442320f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-confirm</value>
      <webElementGuid>fe2b3940-2ce9-4023-a1c1-2797443aa81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>5d8eba91-ea9e-41d9-a695-de8cd5f1b113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c7ab6844-c08b-42a5-a6a8-93551ad01c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-confirm&quot;)</value>
      <webElementGuid>525d52f0-ff5e-47ed-ae59-a37d664665a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-confirm']</value>
      <webElementGuid>b27782ff-afba-4eeb-8044-026f2c3d5933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-checkout-confirm']/div/div[3]/div/input</value>
      <webElementGuid>a5584d87-8e9b-42c5-a568-5a075bb48e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[3]/div/input</value>
      <webElementGuid>2f92e0f6-9370-4473-92e6-5f8055fbcfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-confirm']</value>
      <webElementGuid>85723cd2-8937-4f85-81d1-9d80c44fc5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
