<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post Code_postcode</name>
   <tag></tag>
   <elementGuidId>02797e06-7af2-4877-81cb-6035f0ed799c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-payment-postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-payment-postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Post Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fee9f30f-d21c-4a5f-b9b9-980f31febf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17f4b399-ebce-43ff-8c1f-fdb75577cc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>1fceb302-9fd6-4f41-a00f-b0cfa6f5a8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Post Code</value>
      <webElementGuid>3e0253b4-3d19-424f-9b10-f0f221761ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-postcode</value>
      <webElementGuid>b8af3dc9-572c-434a-8d32-75b5beb0fb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39e473a2-b811-433a-bb46-bef72eb656f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-postcode&quot;)</value>
      <webElementGuid>4597ec1f-726b-47fa-860e-361cd2c9c829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-payment-postcode']</value>
      <webElementGuid>a933c6c8-5670-4e44-9b8f-b22d714f82c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='address']/div[5]/input</value>
      <webElementGuid>149e6585-2d0a-4a6c-ab50-601b71412a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[5]/input</value>
      <webElementGuid>99126980-79ec-4383-8904-5fa46a0fcdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'postcode' and @placeholder = 'Post Code' and @id = 'input-payment-postcode']</value>
      <webElementGuid>1d7f9dbb-18ef-4b42-b0c0-822b8cec54d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
