<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- AmazonasAntioq_dbd715</name>
   <tag></tag>
   <elementGuidId>1a9d4bff-caff-4e14-bd25-2f773a66ad94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-payment-zone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-payment-zone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Region / State&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>76c712dc-2f9e-4a77-be8e-afed01e8bf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>2178ccd5-38f8-411e-8c2c-d42c7aa3d6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-zone</value>
      <webElementGuid>b1de774a-21e0-4073-ad9f-3e715456afa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>71a9d8c2-de24-498b-92c6-a8b1cd33977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- AmazonasAntioquiaAraucaAtlanticoBogota D.C.BolivarBoyacaCaldasCaquetaCasanareCaucaCesarChocoCordobaCundinamarcaGuainiaGuajiraGuaviareHuilaMagdalenaMetaNarinoNorte de SantanderPutumayoQuindioRisaraldaSan Andres y ProvidenciaSantanderSucreTolimaValle del CaucaVaupesVichada</value>
      <webElementGuid>60085d73-c388-43de-b67e-18ba55d14201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-zone&quot;)</value>
      <webElementGuid>02b43d8b-345d-497c-b7e7-ed0fc8a203dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-payment-zone']</value>
      <webElementGuid>4eff6057-d556-40ce-98fc-6f6c78f4cd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='address']/div[7]/select</value>
      <webElementGuid>a44a08b9-bbe1-4e38-9e9b-56134c6e4ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>86763fee-9367-4c21-b540-1e1ef4f1b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>36f08205-1afb-49e9-bd4e-3dbabe480078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3: Delivery Details'])[1]/preceding::select[1]</value>
      <webElementGuid>a8a28238-df4f-4052-b9df-b7773bada5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>6704d5b9-3987-47fc-acd7-4514a9c9d772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-payment-zone' and (text() = ' --- Please Select --- AmazonasAntioquiaAraucaAtlanticoBogota D.C.BolivarBoyacaCaldasCaquetaCasanareCaucaCesarChocoCordobaCundinamarcaGuainiaGuajiraGuaviareHuilaMagdalenaMetaNarinoNorte de SantanderPutumayoQuindioRisaraldaSan Andres y ProvidenciaSantanderSucreTolimaValle del CaucaVaupesVichada' or . = ' --- Please Select --- AmazonasAntioquiaAraucaAtlanticoBogota D.C.BolivarBoyacaCaldasCaquetaCasanareCaucaCesarChocoCordobaCundinamarcaGuainiaGuajiraGuaviareHuilaMagdalenaMetaNarinoNorte de SantanderPutumayoQuindioRisaraldaSan Andres y ProvidenciaSantanderSucreTolimaValle del CaucaVaupesVichada')]</value>
      <webElementGuid>8eb73a96-7ab3-41af-92e3-6a8c1dd572bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
